[firebase]
# Streamlit Cloud にデプロイ時にjsonファイルを読み込めないため、secrets.jsonの中身をこちらに記述する
type = ""
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""
universe_domain = ""

[app]
# アプリケーション設定をここに追加可能
database_url = ""
user_type = ["", "", ...]
